Colour + compass for turning
zockerhuhn/Arduino-4.0-2024_2025 pull request #51
Opened 2024-11-27 14:43 UTC by FlederJ

adjusted colour delays for moving
added lights to show which way it will turn
kreuzung logic adapted to frontalLine and sideLine scenario without straighten()
color calibrates, closes #47 
close #31 
added turning by degrees with compass, close #30

2024-11-27 15:09 UTC, zockerhuhn requested changes
Change red to work

2024-12-03 11:55 UTC, zockerhuhn requested changes
Either red isn't working yet or the code contains a lot of unnecessary comments

2024-12-03 11:55 UTC, zockerhuhn commented on programs/Main/kreuzung.h
Use factor for straight() in line 26

2024-12-11 14:02 UTC, FlederJ commented on programs/Main/kreuzung.h
done

2024-12-11 14:32 UTC, zockerhuhn approved these changes
seems good now

2024-12-11 15:01 UTC, FlederJ commented on programs/Main/Main.ino
please state which comments you consider to be unnecessary

2024-12-11 15:04 UTC, FlederJ commented on programs/Main/Main.ino
but the important thing is that everything seems to work for now (except the bumpers), and there is a possibility for a softlock, but it's mostly correct

2024-12-12 12:49 UTC, merged